<a href="https://colab.research.google.com/github/amirrouh/test/blob/master/np_hw_rabina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#question number 1
import numpy as np
a=[10,12,19,17,-13,18,27,20,-12,-17]       #list assignment
a_list=np.array(a)                         #converting list into numpy array
comp = 20                                  #assigning comparing value
a_list_sorted=[i for i in a_list if abs(i) < comp]   #list with abs value less than 20
print(a_list_sorted)

In [ ]:
# Question number 2
#creating numpy array with dimension 10,2,5 using arange
b=np.arange(100)
b_divide= np.reshape(b,(10,2,5))
print(b_divide)


In [ ]:
#question 3
c=np.arange(21)
c_modify=[]
for i in c:
  if i > 8 and i < 16:
    i = -1 * i
    c_modify.append(i)

  else:
    c_modify.append(i)


print(c_modify)

[0, 1, 2, 3, 4, 5, 6, 7, 8, -9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19, 20]


In [ ]:
#question number 4
d= np.arange(10,22)
d_reshape=np.reshape(d,(3,4))
print(d_reshape)

In [ ]:
#question 5
e= np.zeros((5,5))
e[0,0]=1
e[1,1]=2
e[2,2]=3
e[3,3]=4
e[4,4]=5

print(e)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
#question 6
f_1=np.arange(1,5)
f_2=np.arange(5,9)

f_1=np.reshape(f_1,(2,2))
f_2= np.reshape(f_2,(2,2))

f_3= np.dot(f_1,f_2)
print(f_3)


[[19 22]
 [43 50]]


In [ ]:
#question 7
g=np.array([1,2,3,4,5])

g[:,np.newaxis]+g


array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])